add check-commit-signing action
Chia-Network/actions pull request #47
Opened 2022-11-15 20:06 UTC by altendky

2022-11-18 01:43 UTC, cmmarslender commented
> The biggest question here is what exact signing status do we require. I'm not sure if we have access to any information to do anything beyond just 'was signed by something'.

I think especially for a first pass, "signed by something" is fine. Would be nice to be able to see if its signed by something that GitHub also considers "verified" for the user, but I dont think the commit enforcement necessarily requires that right now.

2022-11-18 01:49 UTC, cmmarslender reviewed
Look good overall. Do you mind adding an action specific readme? Trying to make sure we get those when possible for new actions (and backfilling old ones as we have time)

2022-11-18 17:13 UTC, altendky commented
Sure thing, I'd call that worthy of a `request changes`.

2022-11-18 17:39 UTC, cmmarslender requested changes
Look good overall. Do you mind adding an action specific readme? Trying to make sure we get those when possible for new actions (and backfilling old ones as we have time)

2022-12-01 05:22 UTC, cmmarslender approved these changes

2022-12-01 05:22 UTC, merged