allow specifying the patch version with setup-python
Chia-Network/actions pull request #87
Opened 2023-03-02 20:59 UTC by altendky

2023-03-04 01:01 UTC, cmmarslender approved these changes

2023-03-29 20:50 UTC, TheLastCicada approved these changes

2023-03-29 20:52 UTC, TheLastCicada requested changes
Can you update the README to document the `allow-prerelease` flag?

2023-03-29 20:57 UTC, TheLastCicada approved these changes

2023-03-30 17:25 UTC, cmmarslender approved these changes

2023-03-30 17:31 UTC, merged